#! /usr/bin/env php

<?php

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

$application = new Symfony\Component\Console\Application('Craft CMS Installer', '1.1.0');
$application->add(new Craft\Installer\NewCommand);

$application->run();