#! /usr/bin/env php

<?php

require __DIR__ . '/vendor/autoload.php';

use Craft\Installer\NewCommand;
use Symfony\Component\Console\Application;

$application = new Application('Craft CMS Installer', '1.0');
$application->add(new NewCommand);

$application->run();